/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.formcontatto.model.impl;

import com.liferay.docs.formcontatto.model.Contatto;
import com.liferay.docs.formcontatto.model.ContattoModel;
import com.liferay.docs.formcontatto.model.ContattoSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Contatto service. Represents a row in the &quot;FC_Contatto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ContattoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContattoImpl}.
 * </p>
 *
 * @author Bruno De Boni
 * @see ContattoImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ContattoModelImpl
	extends BaseModelImpl<Contatto> implements ContattoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contatto model instance should use the <code>Contatto</code> interface instead.
	 */
	public static final String TABLE_NAME = "FC_Contatto";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"contattoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"cognome", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"formContattoId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contattoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cognome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("formContattoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FC_Contatto (uuid_ VARCHAR(75) null,contattoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,nome VARCHAR(75) null,cognome VARCHAR(75) null,email VARCHAR(75) null,formContattoId LONG)";

	public static final String TABLE_SQL_DROP = "drop table FC_Contatto";

	public static final String ORDER_BY_JPQL = " ORDER BY contatto.nome ASC";

	public static final String ORDER_BY_SQL = " ORDER BY FC_Contatto.nome ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long FORMCONTATTOID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long NOME_COLUMN_BITMASK = 16L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Contatto toModel(ContattoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Contatto model = new ContattoImpl();

		model.setUuid(soapModel.getUuid());
		model.setContattoId(soapModel.getContattoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setNome(soapModel.getNome());
		model.setCognome(soapModel.getCognome());
		model.setEmail(soapModel.getEmail());
		model.setFormContattoId(soapModel.getFormContattoId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Contatto> toModels(ContattoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Contatto> models = new ArrayList<Contatto>(soapModels.length);

		for (ContattoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ContattoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contattoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContattoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contattoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Contatto.class;
	}

	@Override
	public String getModelClassName() {
		return Contatto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Contatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Contatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contatto, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Contatto)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Contatto, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Contatto, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Contatto)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Contatto, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Contatto, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Contatto>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Contatto.class.getClassLoader(), Contatto.class,
			ModelWrapper.class);

		try {
			Constructor<Contatto> constructor =
				(Constructor<Contatto>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Contatto, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Contatto, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Contatto, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Contatto, Object>>();
		Map<String, BiConsumer<Contatto, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Contatto, ?>>();

		attributeGetterFunctions.put("uuid", Contatto::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Contatto, String>)Contatto::setUuid);
		attributeGetterFunctions.put("contattoId", Contatto::getContattoId);
		attributeSetterBiConsumers.put(
			"contattoId", (BiConsumer<Contatto, Long>)Contatto::setContattoId);
		attributeGetterFunctions.put("groupId", Contatto::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Contatto, Long>)Contatto::setGroupId);
		attributeGetterFunctions.put("companyId", Contatto::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Contatto, Long>)Contatto::setCompanyId);
		attributeGetterFunctions.put("userId", Contatto::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Contatto, Long>)Contatto::setUserId);
		attributeGetterFunctions.put("userName", Contatto::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Contatto, String>)Contatto::setUserName);
		attributeGetterFunctions.put("createDate", Contatto::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Contatto, Date>)Contatto::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Contatto::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Contatto, Date>)Contatto::setModifiedDate);
		attributeGetterFunctions.put("status", Contatto::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Contatto, Integer>)Contatto::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", Contatto::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<Contatto, Long>)Contatto::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", Contatto::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<Contatto, String>)Contatto::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", Contatto::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<Contatto, Date>)Contatto::setStatusDate);
		attributeGetterFunctions.put("nome", Contatto::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Contatto, String>)Contatto::setNome);
		attributeGetterFunctions.put("cognome", Contatto::getCognome);
		attributeSetterBiConsumers.put(
			"cognome", (BiConsumer<Contatto, String>)Contatto::setCognome);
		attributeGetterFunctions.put("email", Contatto::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Contatto, String>)Contatto::setEmail);
		attributeGetterFunctions.put(
			"formContattoId", Contatto::getFormContattoId);
		attributeSetterBiConsumers.put(
			"formContattoId",
			(BiConsumer<Contatto, Long>)Contatto::setFormContattoId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getContattoId() {
		return _contattoId;
	}

	@Override
	public void setContattoId(long contattoId) {
		_contattoId = contattoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_columnBitmask = -1L;

		_nome = nome;
	}

	@JSON
	@Override
	public String getCognome() {
		if (_cognome == null) {
			return "";
		}
		else {
			return _cognome;
		}
	}

	@Override
	public void setCognome(String cognome) {
		_cognome = cognome;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public long getFormContattoId() {
		return _formContattoId;
	}

	@Override
	public void setFormContattoId(long formContattoId) {
		_columnBitmask |= FORMCONTATTOID_COLUMN_BITMASK;

		if (!_setOriginalFormContattoId) {
			_setOriginalFormContattoId = true;

			_originalFormContattoId = _formContattoId;
		}

		_formContattoId = formContattoId;
	}

	public long getOriginalFormContattoId() {
		return _originalFormContattoId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Contatto.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Contatto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Contatto toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContattoImpl contattoImpl = new ContattoImpl();

		contattoImpl.setUuid(getUuid());
		contattoImpl.setContattoId(getContattoId());
		contattoImpl.setGroupId(getGroupId());
		contattoImpl.setCompanyId(getCompanyId());
		contattoImpl.setUserId(getUserId());
		contattoImpl.setUserName(getUserName());
		contattoImpl.setCreateDate(getCreateDate());
		contattoImpl.setModifiedDate(getModifiedDate());
		contattoImpl.setStatus(getStatus());
		contattoImpl.setStatusByUserId(getStatusByUserId());
		contattoImpl.setStatusByUserName(getStatusByUserName());
		contattoImpl.setStatusDate(getStatusDate());
		contattoImpl.setNome(getNome());
		contattoImpl.setCognome(getCognome());
		contattoImpl.setEmail(getEmail());
		contattoImpl.setFormContattoId(getFormContattoId());

		contattoImpl.resetOriginalValues();

		return contattoImpl;
	}

	@Override
	public int compareTo(Contatto contatto) {
		int value = 0;

		value = getNome().compareTo(contatto.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Contatto)) {
			return false;
		}

		Contatto contatto = (Contatto)obj;

		long primaryKey = contatto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ContattoModelImpl contattoModelImpl = this;

		contattoModelImpl._originalUuid = contattoModelImpl._uuid;

		contattoModelImpl._originalGroupId = contattoModelImpl._groupId;

		contattoModelImpl._setOriginalGroupId = false;

		contattoModelImpl._originalCompanyId = contattoModelImpl._companyId;

		contattoModelImpl._setOriginalCompanyId = false;

		contattoModelImpl._setModifiedDate = false;

		contattoModelImpl._originalFormContattoId =
			contattoModelImpl._formContattoId;

		contattoModelImpl._setOriginalFormContattoId = false;

		contattoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Contatto> toCacheModel() {
		ContattoCacheModel contattoCacheModel = new ContattoCacheModel();

		contattoCacheModel.uuid = getUuid();

		String uuid = contattoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contattoCacheModel.uuid = null;
		}

		contattoCacheModel.contattoId = getContattoId();

		contattoCacheModel.groupId = getGroupId();

		contattoCacheModel.companyId = getCompanyId();

		contattoCacheModel.userId = getUserId();

		contattoCacheModel.userName = getUserName();

		String userName = contattoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contattoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contattoCacheModel.createDate = createDate.getTime();
		}
		else {
			contattoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contattoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contattoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contattoCacheModel.status = getStatus();

		contattoCacheModel.statusByUserId = getStatusByUserId();

		contattoCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = contattoCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			contattoCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			contattoCacheModel.statusDate = statusDate.getTime();
		}
		else {
			contattoCacheModel.statusDate = Long.MIN_VALUE;
		}

		contattoCacheModel.nome = getNome();

		String nome = contattoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			contattoCacheModel.nome = null;
		}

		contattoCacheModel.cognome = getCognome();

		String cognome = contattoCacheModel.cognome;

		if ((cognome != null) && (cognome.length() == 0)) {
			contattoCacheModel.cognome = null;
		}

		contattoCacheModel.email = getEmail();

		String email = contattoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			contattoCacheModel.email = null;
		}

		contattoCacheModel.formContattoId = getFormContattoId();

		return contattoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Contatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Contatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contatto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Contatto)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Contatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Contatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contatto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Contatto)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Contatto>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _contattoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _nome;
	private String _cognome;
	private String _email;
	private long _formContattoId;
	private long _originalFormContattoId;
	private boolean _setOriginalFormContattoId;
	private long _columnBitmask;
	private Contatto _escapedModel;

}