/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.formcontatto.model.impl;

import com.liferay.docs.formcontatto.model.FormContatto;
import com.liferay.docs.formcontatto.model.FormContattoModel;
import com.liferay.docs.formcontatto.model.FormContattoSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the FormContatto service. Represents a row in the &quot;FC_FormContatto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>FormContattoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormContattoImpl}.
 * </p>
 *
 * @author Bruno De Boni
 * @see FormContattoImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class FormContattoModelImpl
	extends BaseModelImpl<FormContatto> implements FormContattoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form contatto model instance should use the <code>FormContatto</code> interface instead.
	 */
	public static final String TABLE_NAME = "FC_FormContatto";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"formContattoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("formContattoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FC_FormContatto (uuid_ VARCHAR(75) null,formContattoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FC_FormContatto";

	public static final String ORDER_BY_JPQL =
		" ORDER BY formContatto.formContattoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FC_FormContatto.formContattoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long FORMCONTATTOID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FormContatto toModel(FormContattoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FormContatto model = new FormContattoImpl();

		model.setUuid(soapModel.getUuid());
		model.setFormContattoId(soapModel.getFormContattoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FormContatto> toModels(FormContattoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FormContatto> models = new ArrayList<FormContatto>(
			soapModels.length);

		for (FormContattoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public FormContattoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _formContattoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFormContattoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _formContattoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FormContatto.class;
	}

	@Override
	public String getModelClassName() {
		return FormContatto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FormContatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FormContatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormContatto, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FormContatto)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FormContatto, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FormContatto, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FormContatto)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FormContatto, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FormContatto, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FormContatto>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FormContatto.class.getClassLoader(), FormContatto.class,
			ModelWrapper.class);

		try {
			Constructor<FormContatto> constructor =
				(Constructor<FormContatto>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<FormContatto, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FormContatto, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FormContatto, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FormContatto, Object>>();
		Map<String, BiConsumer<FormContatto, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FormContatto, ?>>();

		attributeGetterFunctions.put("uuid", FormContatto::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<FormContatto, String>)FormContatto::setUuid);
		attributeGetterFunctions.put(
			"formContattoId", FormContatto::getFormContattoId);
		attributeSetterBiConsumers.put(
			"formContattoId",
			(BiConsumer<FormContatto, Long>)FormContatto::setFormContattoId);
		attributeGetterFunctions.put("groupId", FormContatto::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<FormContatto, Long>)FormContatto::setGroupId);
		attributeGetterFunctions.put("companyId", FormContatto::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<FormContatto, Long>)FormContatto::setCompanyId);
		attributeGetterFunctions.put("userId", FormContatto::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<FormContatto, Long>)FormContatto::setUserId);
		attributeGetterFunctions.put("userName", FormContatto::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<FormContatto, String>)FormContatto::setUserName);
		attributeGetterFunctions.put("createDate", FormContatto::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<FormContatto, Date>)FormContatto::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", FormContatto::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FormContatto, Date>)FormContatto::setModifiedDate);
		attributeGetterFunctions.put("status", FormContatto::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<FormContatto, Integer>)FormContatto::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", FormContatto::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<FormContatto, Long>)FormContatto::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", FormContatto::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<FormContatto, String>)
				FormContatto::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", FormContatto::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<FormContatto, Date>)FormContatto::setStatusDate);
		attributeGetterFunctions.put("name", FormContatto::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<FormContatto, String>)FormContatto::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getFormContattoId() {
		return _formContattoId;
	}

	@Override
	public void setFormContattoId(long formContattoId) {
		_formContattoId = formContattoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FormContatto.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FormContatto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FormContatto toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FormContattoImpl formContattoImpl = new FormContattoImpl();

		formContattoImpl.setUuid(getUuid());
		formContattoImpl.setFormContattoId(getFormContattoId());
		formContattoImpl.setGroupId(getGroupId());
		formContattoImpl.setCompanyId(getCompanyId());
		formContattoImpl.setUserId(getUserId());
		formContattoImpl.setUserName(getUserName());
		formContattoImpl.setCreateDate(getCreateDate());
		formContattoImpl.setModifiedDate(getModifiedDate());
		formContattoImpl.setStatus(getStatus());
		formContattoImpl.setStatusByUserId(getStatusByUserId());
		formContattoImpl.setStatusByUserName(getStatusByUserName());
		formContattoImpl.setStatusDate(getStatusDate());
		formContattoImpl.setName(getName());

		formContattoImpl.resetOriginalValues();

		return formContattoImpl;
	}

	@Override
	public int compareTo(FormContatto formContatto) {
		long primaryKey = formContatto.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FormContatto)) {
			return false;
		}

		FormContatto formContatto = (FormContatto)obj;

		long primaryKey = formContatto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		FormContattoModelImpl formContattoModelImpl = this;

		formContattoModelImpl._originalUuid = formContattoModelImpl._uuid;

		formContattoModelImpl._originalGroupId = formContattoModelImpl._groupId;

		formContattoModelImpl._setOriginalGroupId = false;

		formContattoModelImpl._originalCompanyId =
			formContattoModelImpl._companyId;

		formContattoModelImpl._setOriginalCompanyId = false;

		formContattoModelImpl._setModifiedDate = false;

		formContattoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FormContatto> toCacheModel() {
		FormContattoCacheModel formContattoCacheModel =
			new FormContattoCacheModel();

		formContattoCacheModel.uuid = getUuid();

		String uuid = formContattoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			formContattoCacheModel.uuid = null;
		}

		formContattoCacheModel.formContattoId = getFormContattoId();

		formContattoCacheModel.groupId = getGroupId();

		formContattoCacheModel.companyId = getCompanyId();

		formContattoCacheModel.userId = getUserId();

		formContattoCacheModel.userName = getUserName();

		String userName = formContattoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			formContattoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			formContattoCacheModel.createDate = createDate.getTime();
		}
		else {
			formContattoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			formContattoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			formContattoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		formContattoCacheModel.status = getStatus();

		formContattoCacheModel.statusByUserId = getStatusByUserId();

		formContattoCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = formContattoCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			formContattoCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			formContattoCacheModel.statusDate = statusDate.getTime();
		}
		else {
			formContattoCacheModel.statusDate = Long.MIN_VALUE;
		}

		formContattoCacheModel.name = getName();

		String name = formContattoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			formContattoCacheModel.name = null;
		}

		return formContattoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FormContatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FormContatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormContatto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((FormContatto)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FormContatto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FormContatto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FormContatto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FormContatto)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, FormContatto>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _formContattoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _name;
	private long _columnBitmask;
	private FormContatto _escapedModel;

}